image: node:18-alpine
stages:
  - build
  - package-publish
  - trigger-distro-build

default:
  cache: &default_cache
    key: "Frontend-cache"
    paths:
      - node_modules/
      - .yarn/cache/
      - yarn.lock

      - packages/esm-patient-chart-app/node_modules/
      - packages/esm-patient-chart-app/.yarn/cache/
      - packages/esm-patient-chart-app/dist/
      - packages/esm-patient-chart-app/yarn.lock

      - packages/esm-patient-attachments-app/node_modules/
      - packages/esm-patient-attachments-app/.yarn/cache/
      - packages/esm-patient-attachments-app/dist/
      - packages/esm-patient-attachments-app/yarn.lock

build:
  image: node:18-alpine
  stage: build
  tags:
    - docker-runner
  script:
    - yarn config set -H enableImmutableInstalls false
    - yarn install
    - yarn up @openmrs/openmrs-form-engine-lib@next
    - cd ./packages/esm-patient-chart-app/
    - yarn install
    - yarn run build &
    - cd ../../packages/esm-patient-attachments-app/
    - yarn install
    - yarn run build &
    - wait
  cache:
   <<: *default_cache
package-publish:
  image: node:18-alpine
  stage: package-publish
  tags:
    - docker-runner
  script:
    - apk update && apk add git
    - cd ./packages/esm-patient-chart-app/
    - npm version --legacy-peer-deps --no-git-tag-version "$(node -e "console.log(require('semver').inc(require('./package.json').version, 'patch'))")-pre.$CI_PIPELINE_ID"
    - yarn npm publish --tag next
    - cd ../../packages/esm-patient-attachments-app/
    - npm version --legacy-peer-deps --no-git-tag-version "$(node -e "console.log(require('semver').inc(require('./package.json').version, 'patch'))")-pre.$CI_PIPELINE_ID"
    - yarn npm publish --tag next
    - wait
  cache:
    <<: *default_cache
    policy: pull
trigger_job:
  stage: trigger-distro-build
  only:
    - main
  trigger:
    project: openmrs/openmrs-simc-distro-referenceapplication
