image: node:18-alpine
stages:
  - build
  - package-publish
  - trigger-distro-build

default:
  cache: &default_cache
    key: "Frontend-cache"
    paths:
      - node_modules/
      - .yarn/cache/
      - yarn.lock

      - packages/esm-patient-chart-app/node_modules/
      - packages/esm-patient-chart-app/.yarn/cache/
      - packages/esm-patient-chart-app/dist/
      - packages/esm-patient-chart-app/yarn.lock

      - packages/esm-patient-attachments-app/node_modules/
      - packages/esm-patient-attachments-app/.yarn/cache/
      - packages/esm-patient-attachments-app/dist/
      - packages/esm-patient-attachments-app/yarn.lock

build:
  image: node:18-alpine
  stage: build
  tags:
    - docker-runner
  script:
    - sh build.sh
  cache:
   <<: *default_cache
package-publish:
  image: node:18-alpine
  stage: package-publish
  tags:
    - docker-runner
  script:
    - sh publish.sh
  cache:
    <<: *default_cache
    policy: pull
trigger_job:
  stage: trigger-distro-build
  only:
    - main
  trigger:
    project: openmrs/openmrs-simc-distro-referenceapplication
