nodeLinker: node-modules

npmScopes:
  openmrs:
    npmAlwaysAuth: true
    npmAuthToken: "${CI_JOB_TOKEN}"
    npmPublishRegistry: "https://gitlab.tools.gbooking.ru/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
